print('Please enter the following information:')
first=input('First name: ')
last=input('Last name: ')
email=input('Email address: ')
phone=input('Phone number: ')
job=input('Job title: ')
idnum=input('ID Number: ')
#stretch  challenge
hair=input('Hair color: ')
eyes=input('Eyes: ')
month=input('Month: ')
train=input('Training: ')
print('The ID Card is: ')
print('-------------------------------------------')
print(f'{last.upper()} {first.title()}')
print(f'{job.title()}')
print(f'{idnum}')
print()
print(f'{email}')
print(f'{phone}')
print()
print(f'Hair: {hair.title()}        Eyes: {eyes.title()}')
print(f'Month: {month.title()}    Training: {train.title()}')

print('-------------------------------------------')

